NAME = "JoiningPy"
VERSION = "0.1.0"
AUTHOR = "Dídac"

library_name = "importlib.util"

oneInstall = "pip install pandas"
twoInstall = "pip install numpy"
threeInstall = "pip install requests"
fourInstall = "pip install matplotlib"
fiveInstall = "pip install scikit-learn"
sixInstall = "pip install tensorflow"
sevenInstall = "pip install torch"
eightInstall = "pip install flask"
nineInstall = "pip install django"
tenInstall = "pip install beautifulsoup4"
elevenInstall = "pip install selenium"
twelveInstall = "pip install opencv-python"
thirteenInstall = "pip install pillow"
fourteenInstall = "pip install sqlalchemy"
fifteenInstall = "pip install pygame"
sixteenInstall = "pip install keras"
seventeenInstall = "pip install pytest"
eighteenInstall = "pip install jupyter"
nineteenInstall = "pip install plotly"
twentyInstall = "pip install seaborn"

oneRemove = "pip uninstall pandas"
twoRemove = "pip uninstall numpy"
threeRemove = "pip uninstall requests"
fourRemove = "pip uninstall matplotlib"
fiveRemove = "pip uninstall scikit-learn"
sixRemove = "pip uninstall tensorflow"
sevenRemove = "pip uninstall torch"
eightRemove = "pip uninstall flask"
nineRemove = "pip uninstall django"
tenRemove = "pip uninstall beautifulsoup4"
elevenRemove = "pip uninstall selenium"
twelveRemove = "pip uninstall opencv-python"
thirteenRemove = "pip uninstall pillow"
fourteenRemove = "pip uninstall sqlalchemy"
fifteenRemove = "pip uninstall pygame"
sixteenRemove = "pip uninstall keras"
seventeenRemove = "pip uninstall pytest"
eighteenRemove = "pip uninstall jupyter"
nineteenRemove = "pip uninstall plotly"
twentyRemove = "pip uninstall seaborn"

oneName = "Pandas"
twoName = "Numpy"
threeName = "Requests"
fourName = "Matplotlib"
fiveName = "Scikit-learn"
sixName = "TensorFlow"
sevenName = "PyTorch"
eightName = "Flask"
nineName = "Django"
tenName = "BeautifulSoup"
elevenName = "Selenium"
twelveName = "OpenCV"
thirteenName = "Pillow"
fourteenName = "SQLAlchemy"
fifteenName = "PyGame"
sixteenName = "Keras"
seventeenName = "Pytest"
eighteenName = "Jupyter"
nineteenName = "Plotly"
twentyName = "Seaborn"


y = "y"
n = "n"

Y = "Y"
N = "N"
